configs:
  secret:
    createSecret: true
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - hurdle-archive.servegame.com
    paths:
      - /argocd
    pathType: Prefix
    https: true
